# Generated by Django 5.1.6 on 2025-04-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleritem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_item_images/'),
        ),
    ]
