# Generated by Django 5.1.6 on 2025-04-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_selleritem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='localitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='local_item_images/'),
        ),
    ]
