# Generated by Django 5.1.6 on 2025-04-11 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalHomeMadeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, unique=True)),
                ('price', models.FloatField()),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='global_homemade_items/')),
                ('homemade_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_homemade_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeMadeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='homemade_items/')),
                ('homemade_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homemade_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
