# Generated by Django 5.1.6 on 2025-04-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemadeitem',
            name='order_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homemadeitem',
            name='order_limit',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
